name: Tag It

# Controls when the workflow will run
on:
  workflow_dispatch:
  pull_request:
    types: [ closed ] 
    branches: [ main ]


# Tag jobs
jobs:
  tag-pr: 
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3
      - name: Tag It
      # Get the version number from react-frontend/package.json
        run: | 
          version=$(cat package.json | jq '.version' | tr -d '"')
          echo "version: $version"
          git tag $version
          git push -u origin $version